### ISSUE TITLE
Django 프로젝트 및 앱 생성

### ISSUE THREAD

**Issue by Jeldo** [psymoney/stocker#3]
- [x] backend 하위 경로에 server 프로젝트 생성
- [x] backend/apps 하위 경로에 financials app을 생성
- [x] backend 하위 경로에 .gitignore 생성 (기존 방식 유지)

### 예시

Project 이름: server
App 이름: financials

frontend
backend
ㄴmanage.py
ㄴ.gitignore
...
ㄴserver
ㄴㄴ__init__.py
   ...
ㄴapps
ㄴㄴfinancials
...

더 좋은 이름이나 구조가 있으면 변경 가능

**Comment by psymoney** [comment]
App 이름 변경: statement -> financials
